### ISSUE TITLE
Fontain doesn't work with RecyclerView?

### ISSUE THREAD

**Issue by vfongmala** [scopely/fontain#4]
Font doesn't apply to view under `RecyclerView`. So I workaround by apply on ViewHolder.
Any suggestion?

**Comment by PeterAttardo** [comment]
Because `RecyclerView` can be creating, adding, and removing views from its view hierarchy at any time, Fontain will not be able to access all existing and potentially future-existing views from the `RecyclerView` alone. The appropriate place to inject would be in the `onCreateViewHolder` method of the `RecyclerView.Adapter`. You can either apply fonts to the newly created views before instantiating a `ViewHolder` with them, or simply inflate them from XML that has the font properties already set. That seems to be what you're already doing.
