### ISSUE TITLE
For Wear OS fonts are not loaded at all

### ISSUE THREAD

**Issue by Duna** [scopely/fontain#7]
I have an Wear 2.0 Activity and a TextView which uses a custom font. When deploy the app to wear devices the font is not loaded, using real device LG Urbane 2(on simulator is loaded ok). Tried with different custom fonts. I have set the custom font in app style level and in activity layout textview. Text size is set to 16sp. AndroidX imports used.

```
<item name="android:fontFamily">@font/lalezar</item>

<TextView
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:fontFamily="@font/lalezar"/>
```
Font used:​ Lalezar-Regular.ttf etc...

I am doing something wrong? Is this a BUG?

**Comment by PeterAttardo** [comment]
This library predates the introduction of android's `@font` resource, which was introduced in API 26 (8.0). If you want to use the `@font` resource way of doing things, any bugs or issues you come across would have to be addressed to the official Android documentation. The issue you are likely encountering is that Wear 2.0 is listed as being based off of Android 7.1.1/8.0.0. 7.1.1 does not support `@font` resources, while 8.0.0 does, so it might be that the LG Urbane 2 uses a version built off of 7.1.1, while your emulator is using an 8.0.0-based version. I don't have much experience with Wear O.S. so I unfortunately can't be more helpful than that.

If you wish to use Fontain's way of doing things, then the readme on the main page explains how to go about it. Font files would be places in the `assets/` folder as described (instead of `res/fonts/`), and instead of a regular TextView you would use an instance of `com.scopely.fontain.views.FontTextView`. The font family would be referenced in XML with app:font_family (as it is a custom attribute, not an android: attribute).

**Comment by Duna** [comment]
Thank you for clarifications!
